@extends('layouts.app')
@section('title', 'Search Ethiopia')
@section('content')
<div class="container py-4 py-lg-5">
    <div class="mb-4"><p class="text-uppercase text-success small fw-semibold mb-1">Discover Ethiopia</p><h1 class="display-6 fw-semibold mb-2">Search places, experiences, and services</h1><p class="text-muted mb-0">Find public tourism information without needing to know which part of Ethio Tour provides it.</p></div>
    <form class="card border-0 shadow-sm mb-4" method="GET" action="{{ route('search') }}"><div class="card-body"><div class="row g-3 align-items-end"><div class="col-lg-4"><label class="form-label" for="search-query">Search</label><input class="form-control form-control-lg" id="search-query" name="q" value="{{ $filters['q'] }}" placeholder="Try Gondar, castle, hotel…" autofocus></div><div class="col-md-3 col-lg-2"><label class="form-label" for="search-type">Type</label><select class="form-select" id="search-type" name="type"><option value="">All types</option>@foreach($types as $type)<option value="{{ $type }}" @selected($filters['type'] === $type)>{{ ucfirst(str_replace('_', ' ', $type)) }}</option>@endforeach</select></div><div class="col-md-3 col-lg-2"><label class="form-label" for="search-destination">Destination</label><select class="form-select" id="search-destination" name="destination"><option value="">All destinations</option>@foreach($destinations as $destination)<option value="{{ $destination->destination_id }}" @selected($filters['destination'] === $destination->destination_id)>{{ $destination->name }}</option>@endforeach</select></div><div class="col-md-3 col-lg-2"><label class="form-label" for="search-category">Category</label><select class="form-select" id="search-category" name="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->category_id }}" @selected($filters['category'] === $category->category_id)>{{ $category->category_name }}</option>@endforeach</select></div><div class="col-md-3 col-lg-2"><label class="form-label" for="search-rating">Minimum rating</label><select class="form-select" id="search-rating" name="rating"><option value="">Any rating</option>@for($rating = 5; $rating >= 1; $rating--)<option value="{{ $rating }}" @selected((string) $filters['rating'] === (string) $rating)>{{ $rating }}+ / 5</option>@endfor</select></div><div class="col-md-3 col-lg-2"><label class="form-label" for="search-date">Event date</label><input class="form-control" id="search-date" name="date" type="date" value="{{ $filters['date'] }}"><button class="btn btn-success w-100 mt-2" type="submit">Search</button></div></div></div></form>
    <div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">{{ $results->total() }} {{ $results->total() === 1 ? 'result' : 'results' }}</h2>@if($filters['q'] || $filters['type'] || $filters['destination'] || $filters['category'] || $filters['date'] || $filters['rating'])<a class="small" href="{{ route('search') }}">Clear filters</a>@endif</div>
    @if($results->isEmpty())
        <x-ui.empty-state title="No public results found" message="Try a broader search or remove one of the filters." />
    @else
        <div class="row g-4">@foreach($results as $result)<div class="col-md-6 col-xl-4"><article class="card border-0 shadow-sm h-100"><div class="card-body d-flex flex-column"><div class="d-flex justify-content-between gap-2 mb-2"><span class="badge text-bg-light text-success">{{ $result['type_label'] }}</span>@if($result['destination'])<span class="small text-muted text-truncate">{{ $result['destination'] }}</span>@endif</div><h3 class="h5">{{ $result['title'] }}</h3><p class="text-muted small flex-grow-1">{{ substr((string) ($result['summary'] ?: 'Public tourism information'), 0, 150) }}</p>@if($result['rating'] !== null)<p class="small text-warning mb-3">{{ number_format($result['rating'], 1) }} / 5 rating</p>@endif<div class="d-flex gap-2"><a class="btn btn-outline-success btn-sm" href="{{ $result['url'] }}">View details</a>@if($result['map_url'])<a class="btn btn-outline-secondary btn-sm" href="{{ $result['map_url'] }}">View on map</a>@endif</div></div></article></div>@endforeach</div><div class="mt-4">{{ $results->links() }}</div>
    @endif
</div>
@endsection
