@extends('layouts.app')
@section('title', 'Bureau Dashboard')
@section('content')
<div class="container-fluid py-4 py-lg-5"><div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><p class="text-uppercase text-muted small fw-semibold mb-1">Regulatory operations</p><h1 class="h2 mb-1">Tourism Bureau workspace</h1><p class="text-muted mb-0">Review verification queues and maintain trusted tourism information.</p></div><span class="badge text-bg-info px-3 py-2">Bureau authority</span></div>
<section aria-labelledby="attention-heading" class="mb-4"><h2 id="attention-heading" class="h5 mb-3">Needs attention</h2><div class="row g-3"><div class="col-md-6"><div class="card border-warning shadow-sm h-100"><div class="card-body"><span class="badge text-bg-warning text-dark mb-2">Guide queue</span><h3 class="h5">{{ $pendingGuides }} guide{{ $pendingGuides === 1 ? '' : 's' }} awaiting verification</h3><p class="small text-muted">Review identity and professional information before deciding.</p><a class="btn btn-warning" href="{{ route('bureau.guides.index', ['status'=>'pending']) }}">Review guide queue</a></div></div></div><div class="col-md-6"><div class="card border-warning shadow-sm h-100"><div class="card-body"><span class="badge text-bg-warning text-dark mb-2">Provider queue</span><h3 class="h5">{{ $pendingProviders }} provider{{ $pendingProviders === 1 ? '' : 's' }} awaiting verification</h3><p class="small text-muted">A Bureau decision does not activate the provider platform account.</p><a class="btn btn-warning" href="{{ route('bureau.providers.index', ['status'=>'pending']) }}">Review provider queue</a></div></div></div></div></section>
<section aria-labelledby="summary-heading" class="mb-4"><h2 id="summary-heading" class="h5 mb-3">Verification summary</h2><div class="row g-3"><div class="col-6 col-lg-3"><a class="card border-0 shadow-sm h-100 text-decoration-none" href="{{ route('bureau.guides.index', ['status'=>'verified']) }}"><div class="card-body"><div class="small text-muted">Verified guides</div><div class="display-6 text-success">{{ $verifiedGuides }}</div></div></a></div><div class="col-6 col-lg-3"><a class="card border-0 shadow-sm h-100 text-decoration-none" href="{{ route('bureau.providers.index', ['status'=>'verified']) }}"><div class="card-body"><div class="small text-muted">Verified providers</div><div class="display-6 text-success">{{ $approvedProviders }}</div></div></a></div><div class="col-6 col-lg-3"><a class="card border-0 shadow-sm h-100 text-decoration-none" href="{{ route('bureau.museums.index') }}"><div class="card-body"><div class="small text-muted">Museum records</div><div class="display-6 text-primary">{{ $museumCount }}</div></div></a></div><div class="col-6 col-lg-3"><a class="card border-0 shadow-sm h-100 text-decoration-none" href="{{ route('bureau.reports.index') }}"><div class="card-body"><div class="small text-muted">Reports</div><div class="display-6 text-info">View</div></div></a></div></div></section>
<div class="row g-4"><section class="col-xl-7" aria-labelledby="decisions-heading"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white"><h2 id="decisions-heading" class="h5 mb-1">Recent decisions</h2><p class="small text-muted mb-0">Recorded regulatory decisions from the central audit service.</p></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Action</th><th>Officer</th><th>When</th></tr></thead><tbody>@forelse($recentDecisions as $decision)<tr><td class="fw-semibold">{{ str_replace('_',' ',ucfirst($decision->action)) }}</td><td>{{ $decision->actor?->email ?? 'System' }}</td><td class="text-nowrap text-muted">{{ $decision->created_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-4">No Bureau decisions have been recorded yet.</td></tr>@endforelse</tbody></table></div></div></section><section class="col-xl-5" aria-labelledby="operations-heading"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white"><h2 id="operations-heading" class="h5 mb-1">Museum / tourism operations</h2><p class="small text-muted mb-0">Keep public cultural information current.</p></div><div class="card-body"><p class="text-muted">{{ $museumCount }} museum record{{ $museumCount === 1 ? '' : 's' }} are managed by this Bureau account.</p><a class="btn btn-outline-primary" href="{{ route('bureau.museums.index') }}">Manage museums</a></div></div></section></div>
</div>
@endsection
