@extends('layouts.app')

@section('title', $service->service_name)

@section('content')
<div class="container py-4">
    <a class="link-secondary d-inline-block mb-3" href="{{ route('transportation.index') }}">&larr; Back to transportation</a>
    <div class="row g-4">
        <div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-body p-4"><p class="text-uppercase small text-primary fw-semibold mb-1">Transportation service</p><h1 class="h2">{{ $service->service_name }}</h1><p class="text-muted">{{ $service->serviceProvider->business_name }} · {{ $service->destination->name }}</p><p>{{ $service->description }}</p><div class="alert alert-light border mb-0">Daily rental rate: <strong>{{ number_format($service->price, 2) }} ETB</strong>. Your final booking amount is calculated from the requested rental duration and is payable after acceptance.</div></div></div><div class="card border-0 shadow-sm mt-4"><div class="card-header bg-white"><h2 class="h5 mb-0">Available vehicle inventory</h2></div><div class="card-body">@forelse ($service->transportationVehicles as $vehicle)<div class="border-bottom py-2"><strong>{{ $vehicle->vehicle_identifier }}</strong> · {{ $vehicle->vehicle_type }} · capacity {{ $vehicle->capacity }}@if($vehicle->make || $vehicle->model) · {{ trim($vehicle->make.' '.$vehicle->model) }}@endif</div>@empty<p class="text-muted mb-0">No active vehicles are currently published.</p>@endforelse</div></div></div>
        <div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5">Request transportation</h2><p class="small text-muted">Enter your route and rental window. A provider will review the request before payment.</p><form method="POST" action="{{ route('tourist.transportation-reservations.store', $service) }}">@csrf<div class="mb-3"><label class="form-label">Pickup location</label><input name="pickup_location" value="{{ old('pickup_location') }}" class="form-control" required></div><div class="mb-3"><label class="form-label">Drop-off location</label><input name="dropoff_location" value="{{ old('dropoff_location') }}" class="form-control" required></div><div class="mb-3"><label class="form-label">Pickup</label><input type="datetime-local" name="pickup_at" value="{{ old('pickup_at') }}" class="form-control" required></div><div class="mb-3"><label class="form-label">Drop-off</label><input type="datetime-local" name="dropoff_at" value="{{ old('dropoff_at') }}" class="form-control" required></div><div class="mb-3"><label class="form-label">Passengers</label><input type="number" name="passenger_count" min="1" value="{{ old('passenger_count', 1) }}" class="form-control" required></div>@guest<p class="small text-muted">Please log in as a tourist to submit a request.</p>@endguest<button class="btn btn-primary w-100" @guest disabled @endguest>Submit request</button></form></div></div></div>
    </div>
</div>
@endsection
