@extends('layouts.app')

@section('title', 'Hotel Dashboard · '.$provider->business_name)

@section('content')
<div class="container-fluid py-4 py-lg-5 px-3 px-lg-5">
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4 pb-3 border-bottom"><div><p class="text-uppercase text-muted small fw-semibold mb-1">Hotel portal</p><h1 class="h3 mb-1">{{ $provider->business_name }}</h1><p class="text-secondary mb-0">{{ $provider->user?->email }}</p></div><div class="d-flex gap-2"><a class="btn btn-dark btn-sm" href="{{ route('hotel.rooms.create') }}">Add room</a><a class="btn btn-outline-secondary btn-sm" href="{{ route('hotel.profile') }}">Profile</a></div></div>
    <h2 class="h5 mb-3">Needs attention</h2>
    @if($stats['pendingAttention'] > 0)<div class="alert alert-warning">{{ $stats['pendingAttention'] }} reservation request(s) are waiting. <a href="{{ route('hotel.reservations.index', ['status' => 'pending']) }}">Review reservations</a></div>@else<div class="alert alert-success">No hotel reservation requests are waiting.</div>@endif
    <div class="d-flex flex-wrap gap-3 small mb-3"><a href="{{ route('hotel.services.index') }}">Room-type services</a><a href="{{ route('hotel.rooms.index') }}">Physical rooms</a><a href="{{ route('hotel.reservations.index') }}">Reservations</a><span class="text-muted">Guest feedback: {{ $stats['reviewCount'] > 0 ? $stats['reviewCount'].' recorded' : 'no reviews recorded' }}</span></div>
    <div class="row g-3 mb-4">
        <div class="col-6 col-xl-3"><div class="card border-0 shadow-sm rounded-4 h-100 p-3"><span class="small text-muted text-uppercase fw-bold">Rooms</span><strong class="h3 mt-2">{{ $stats['totalRooms'] }}</strong><span class="small text-muted">{{ $stats['activeRooms'] }} Active rooms · {{ $stats['inactiveRooms'] }} inactive</span></div></div>
        <div class="col-6 col-xl-3"><div class="card border-0 shadow-sm rounded-4 h-100 p-3"><span class="small text-muted text-uppercase fw-bold">Occupancy</span><strong class="h3 mt-2">{{ $stats['occupancyRate'] !== null ? $stats['occupancyRate'].'%' : 'Not available' }}</strong><span class="small text-muted">Based on current room reservations</span></div></div>
        <div class="col-6 col-xl-3"><div class="card border-0 shadow-sm rounded-4 h-100 p-3"><span class="small text-muted text-uppercase fw-bold">7-day revenue</span><strong class="h3 mt-2">{{ number_format($stats['weeklyRevenue'], 2) }} ETB</strong><span class="small text-muted">Confirmed and completed bookings</span></div></div>
        <div class="col-6 col-xl-3"><div class="card border-0 shadow-sm rounded-4 h-100 p-3"><span class="small text-muted text-uppercase fw-bold">Reviews</span>@if($stats['reviewCount'] > 0)<strong class="h3 mt-2">{{ number_format($stats['reviewAverage'], 1) }} / 5</strong><span class="small text-muted">{{ $stats['reviewCount'] }} recorded</span>@else<strong class="h5 mt-2">No reviews yet</strong><span class="small text-muted">No review records</span>@endif</div></div>
    </div>
    <div class="row g-4">
        <div class="col-lg-7"><div class="card border-0 shadow-sm rounded-4"><div class="card-header bg-white d-flex justify-content-between"><h2 class="h5 mb-0">7-day revenue activity</h2><span class="small text-muted">{{ number_format($stats['weeklyRevenue'], 2) }} ETB</span></div><div class="card-body">@if($stats['weeklyRevenue'] > 0)<div class="d-flex align-items-end gap-2" style="height: 150px">@foreach($stats['weeklyChartDays'] as $day)<div class="flex-fill text-center"><div class="bg-success rounded-top" style="height: {{ max(2, $day['height']) }}%;" title="{{ $day['day'] }}: {{ number_format($day['amount'], 2) }} ETB"></div><small class="text-muted">{{ $day['day'] }}</small></div>@endforeach</div>@else<div class="text-muted py-5 text-center">No confirmed or completed hotel revenue in the last seven days.</div>@endif</div></div></div>
        <div class="col-lg-5"><div class="card border-0 shadow-sm rounded-4"><div class="card-header bg-white"><h2 class="h5 mb-0">Recent bookings</h2></div><div class="list-group list-group-flush">@forelse($recentBookings as $booking)<div class="list-group-item"><strong>{{ $booking->tourismService?->service_name ?: 'Hotel service' }}</strong><small class="d-block text-muted">{{ $booking->tourist?->full_name ?: $booking->tourist?->user?->email ?: 'Tourist' }} · #{{ $booking->booking_id }}</small><span class="badge text-bg-light border mt-1">{{ $booking->status === 'payment_pending' ? 'Awaiting Payment' : ucfirst($booking->status) }} · {{ $booking->total_amount !== null ? number_format((float) $booking->total_amount, 2).' '.$booking->currency : 'Amount not set' }}</span></div>@empty<div class="list-group-item text-muted">No hotel bookings recorded yet.</div>@endforelse</div><div class="card-footer bg-white"><a href="{{ route('hotel.reservations.index') }}" class="small">View all reservations</a></div></div></div>
    </div>
</div>
@endsection
