@extends('layouts.app')
@section('title', 'Subscriptions')
@section('content')
<div class="container-fluid py-4">
    <div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-1">Subscription Plans</h1><p class="text-muted mb-0">Plan availability and commission rates are configuration only; payment settlement is deferred.</p></div></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route('admin.subscriptions.store') }}" class="card card-body mb-4"><div class="row g-2 align-items-end">@csrf<div class="col-md-3"><label class="form-label">Plan name</label><input class="form-control" name="plan" value="{{ old('plan') }}" required></div><div class="col-md-2"><label class="form-label">Price</label><input class="form-control" name="price" type="number" min="0" step="0.01" value="{{ old('price') }}"></div><div class="col-md-2"><label class="form-label">Commission %</label><input class="form-control" name="commission_rate" type="number" min="0" max="100" step="0.01" value="{{ old('commission_rate') }}" required></div><div class="col-md-2"><label class="form-label">Duration (days)</label><input class="form-control" name="duration" type="number" min="1" value="{{ old('duration') }}" required></div><div class="col-md-2"><button class="btn btn-primary">Add plan</button></div></div></form>
    <div class="card shadow-sm mb-4"><div class="card-header bg-white"><h2 class="h5 mb-0">Plan lifecycle</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Plan</th><th>Price</th><th>Commission</th><th>Duration</th><th>State</th><th>Subscribers</th><th>Actions</th></tr></thead><tbody>@forelse($plans as $plan)<tr><form method="POST" action="{{ route('admin.subscriptions.update',$plan) }}">@csrf @method('PUT')<td><input class="form-control" name="plan" value="{{ $plan->plan }}"></td><td><input class="form-control" name="price" type="number" min="0" step="0.01" value="{{ $plan->price }}"></td><td><input class="form-control" name="commission_rate" type="number" min="0" max="100" step="0.01" value="{{ $plan->commission_rate }}"></td><td><input class="form-control" name="duration" type="number" min="1" value="{{ $plan->duration }}"></td><td><x-ui.status-badge :status="$plan->active ? 'active' : 'inactive'" /></td><td>{{ $plan->provider_subscriptions_count }}</td><td class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary">Save</button></form><form method="POST" action="{{ route('admin.subscriptions.status',$plan) }}">@csrf @method('PATCH')<input type="hidden" name="active" value="{{ $plan->active ? 0 : 1 }}"><button class="btn btn-sm {{ $plan->active ? 'btn-outline-warning' : 'btn-outline-success' }}">{{ $plan->active ? 'Deactivate' : 'Activate' }}</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No plans configured.</td></tr>@endforelse</tbody></table></div></div>
    <div class="card shadow-sm"><div class="card-header bg-white"><h2 class="h5 mb-0">Provider subscriptions</h2></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Provider</th><th>Plan</th><th>State</th><th>Start</th><th>End</th></tr></thead><tbody>@forelse($subscriptions as $subscription)<tr><td>{{ $subscription->serviceProvider?->business_name ?: 'Unknown provider' }}</td><td>{{ $subscription->subscriptionPlan?->plan ?: 'Unknown plan' }}</td><td><x-ui.status-badge :status="$subscription->status" /></td><td>{{ $subscription->start_date?->format('Y-m-d') }}</td><td>{{ $subscription->end_date?->format('Y-m-d') }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">No provider subscriptions recorded.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
