@extends('layouts.app')

@section('title', 'Restaurant Portal · '.$provider->business_name)

@section('content')
<div class="container-fluid py-4 py-lg-5 px-3 px-lg-5">
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4 pb-3 border-bottom"><div><p class="text-uppercase text-muted small fw-semibold mb-1">Restaurant portal</p><h1 class="h3 mb-1">{{ $provider->business_name }}</h1><p class="text-secondary mb-0">{{ $provider->user?->email }}</p></div><div class="d-flex gap-2"><a class="btn btn-dark btn-sm" href="{{ route('restaurant.services.create') }}">Add service</a><a class="btn btn-outline-secondary btn-sm" href="{{ route('restaurant.profile') }}">Profile</a></div></div>
    <h2 class="h5 mb-3">Needs attention</h2>
    @if($stats['pendingReservations'] > 0)<div class="alert alert-warning">{{ $stats['pendingReservations'] }} reservation request(s) are waiting. <a href="{{ route('restaurant.reservations.index', ['status' => 'pending']) }}">Review reservations</a></div>@else<div class="alert alert-success">No restaurant reservation requests are waiting.</div>@endif
    <div class="row g-3 mb-4">
        <div class="col-6 col-xl-3"><div class="card border-0 shadow-sm rounded-4 h-100 p-3"><span class="small text-muted text-uppercase fw-bold">Services</span><strong class="h3 mt-2">{{ $stats['serviceCount'] }}</strong><span class="small text-muted">Published restaurant offerings</span></div></div>
        <div class="col-6 col-xl-3"><div class="card border-0 shadow-sm rounded-4 h-100 p-3"><span class="small text-muted text-uppercase fw-bold">Tables</span><strong class="h3 mt-2">{{ $stats['activeTables'] }} / {{ $stats['tableCount'] }}</strong><span class="small text-muted">Active / total tables</span></div></div>
        <div class="col-6 col-xl-3"><div class="card border-0 shadow-sm rounded-4 h-100 p-3"><span class="small text-muted text-uppercase fw-bold">This month revenue</span><strong class="h3 mt-2">{{ number_format($stats['monthlyRevenue'], 2) }} ETB</strong><span class="small text-muted">Confirmed and completed bookings</span></div></div>
        <div class="col-6 col-xl-3"><div class="card border-0 shadow-sm rounded-4 h-100 p-3"><span class="small text-muted text-uppercase fw-bold">Reviews</span>@if($stats['reviewCount'] > 0)<strong class="h3 mt-2">{{ number_format($stats['reviewAverage'], 1) }} / 5</strong><span class="small text-muted">{{ $stats['reviewCount'] }} recorded</span>@else<strong class="h5 mt-2">No reviews yet</strong><span class="small text-muted">No review records</span>@endif</div></div>
    </div>
    <div class="row g-4">
        <div class="col-lg-7"><div class="card border-0 shadow-sm rounded-4"><div class="card-header bg-white d-flex justify-content-between"><div><h2 class="h5 mb-0">Menu performance</h2><small class="text-muted">Booking counts from current records</small></div><a href="{{ route('restaurant.services.index') }}" class="small">Manage</a></div><div class="list-group list-group-flush">@forelse($dishPerformance as $dish)<div class="list-group-item"><div class="d-flex justify-content-between"><strong>{{ $dish['name'] }}</strong><span>{{ $dish['orders'] }} booking(s)</span></div><div class="progress mt-2" style="height: 6px"><div class="progress-bar" style="width: {{ $dish['percentage'] }}%"></div></div><small class="text-muted">{{ number_format($dish['price'], 2) }} ETB · {{ $dish['category'] }}</small></div>@empty<div class="list-group-item text-muted">No restaurant services have been added yet.</div>@endforelse</div></div></div>
        <div class="col-lg-5"><div class="card border-0 shadow-sm rounded-4"><div class="card-header bg-white"><h2 class="h5 mb-0">Recent reservations</h2></div><div class="list-group list-group-flush">@forelse($recentReservations as $booking)<div class="list-group-item"><strong>{{ $booking->tourismService?->service_name ?: 'Restaurant service' }}</strong><small class="d-block text-muted">{{ $booking->tourist?->full_name ?: $booking->tourist?->user?->email ?: 'Tourist' }} · {{ $booking->restaurantReservation?->guest_count ?: 0 }} guest(s)</small><span class="badge text-bg-light border mt-1">{{ ucfirst($booking->status) }}</span></div>@empty<div class="list-group-item text-muted">No restaurant reservations recorded yet.</div>@endforelse</div><div class="card-footer bg-white"><a href="{{ route('restaurant.reservations.index') }}" class="small">View all reservations</a></div></div></div>
    </div>
</div>
@endsection
