@extends('layouts.app')
@section('title', 'Provider Governance')
@section('content')
<div class="container-fluid py-4 py-lg-5">
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><p class="text-uppercase text-muted small fw-semibold mb-1">Administrator workspace</p><h1 class="h2 mb-1">Provider governance</h1><p class="text-muted mb-0">Review the Bureau gate and manage the platform activation state separately.</p></div><span class="badge text-bg-info px-3 py-2">Bureau verification ≠ platform activation</span></div>
    <div class="d-flex flex-wrap gap-2 mb-3" aria-label="Provider queues"><a class="btn btn-sm {{ $verification === 'verified' && $status === 'pending' ? 'btn-primary' : 'btn-outline-primary' }}" href="{{ route('admin.providers.index', ['verification'=>'verified','status'=>'pending']) }}">Activation queue</a><a class="btn btn-sm {{ $status === 'approved' ? 'btn-success' : 'btn-outline-success' }}" href="{{ route('admin.providers.index', ['status'=>'approved']) }}">Approved</a><a class="btn btn-sm {{ $status === 'suspended' ? 'btn-warning' : 'btn-outline-warning' }}" href="{{ route('admin.providers.index', ['status'=>'suspended']) }}">Suspended</a><a class="btn btn-sm {{ $status === 'rejected' ? 'btn-danger' : 'btn-outline-danger' }}" href="{{ route('admin.providers.index', ['status'=>'rejected']) }}">Rejected</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.providers.index') }}">All providers</a></div>
    <form class="card card-body border-0 shadow-sm mb-4" method="GET"><div class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label" for="provider-search">Search</label><input id="provider-search" class="form-control" name="q" value="{{ $search }}" placeholder="Business name or email"></div><div class="col-md-2"><label class="form-label" for="provider-type">Provider type</label><select id="provider-type" class="form-select" name="type"><option value="">All types</option>@foreach(['hotel','restaurant','transportation_car_rental','event_organizer'] as $option)<option value="{{ $option }}" @selected($type === $option)>{{ str_replace('_',' ',ucfirst($option)) }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label" for="bureau-state">Bureau state</label><select id="bureau-state" class="form-select" name="verification"><option value="">All states</option>@foreach(['pending','verified','rejected'] as $option)<option value="{{ $option }}" @selected($verification === $option)>{{ ucfirst($option) }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label" for="platform-state">Platform state</label><select id="platform-state" class="form-select" name="status"><option value="">All states</option>@foreach(['pending','approved','suspended','rejected'] as $option)<option value="{{ $option }}" @selected($status === $option)>{{ ucfirst($option) }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary w-100">Apply filters</button></div></div></form>
    <div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><caption class="visually-hidden">Provider governance records</caption><thead class="table-light"><tr><th>Business</th><th>Type</th><th>Bureau verification</th><th>Platform status</th><th>Account</th><th>Registered</th><th><span class="visually-hidden">Actions</span></th></tr></thead><tbody>@forelse($providers as $provider)<tr><td class="fw-semibold">{{ $provider->business_name }}</td><td>{{ str_replace('_',' ',ucfirst($provider->provider_type)) }}</td><td><x-ui.status-badge :status="$provider->verification_status" /></td><td><x-ui.status-badge :status="$provider->status" /></td><td>{{ $provider->user?->is_active ? 'Active' : 'Inactive' }}</td><td class="text-nowrap">{{ $provider->created_at?->format('Y-m-d') }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.providers.show',$provider) }}">Review</a></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-5">No providers match these filters.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $providers->links() }}</div></div>
</div>
@endsection
